# Generated by Django 2.2.6 on 2019-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
